version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
